openapi: 3.1.0
info:
  version: 1.0.0
  title: Contacts App
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: 
    This is a documentation of Contacts app
tags:
  - name: Contacts
    description: Operations about users.
  - name: Auth
    description: Auth operations.
servers:
  - url: http://localhost:3000
  - url: https://node-js-hw-2-mongodb.onrender.com
paths:
  /contacts:
    get: 
      $ref: ../swagger/path/get.yaml
    post: 
      $ref: ../swagger/path/post.yaml
  /contacts/{id}:
    get:
      $ref: ../swagger/path/{id}/get.yaml
    patch: 
      $ref: ../swagger/path/{id}/patch.yaml
    delete: 
      $ref: ../swagger/path/{id}/delete.yaml
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer